@host = http://localhost:3000

GET {{host}}/api/teams


###
GET {{host}}/api/teams/1
###
GET {{host}}/api/teams/name/lola

###
POST {{host}}/api/teams/create
Content-Type: application/json

{
    "username": "lola",
    "mail": "lola1@gmail.com",
    "password": "12345"
}
###
PUT {{host}}/api/teams/3
Content-Type: application/json

{
    "username": "lola",
    "mail": "lola.robles@gmail.com",
    "password": "12345"
}

###
DELETE  {{host}}/api/teams/3

###############################################################



GET {{host}}/api/teams


###
GET {{host}}/api/teams/1
###
GET {{host}}/api/teams/name/viaje

###
POST {{host}}/api/teams/create
Content-Type: application/json

{
    "name": "cena",
    "description": "cena de amigos"
    
}
###
PUT {{host}}/api/teams/1
Content-Type: application/json

{
     "name": "viaje a Barcelona",
    "description": "viaje de trabajo"
}

###
DELETE  {{host}}/api/teams/1