@host = http://localhost:3000


GET {{host}}/api/users/team/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTczOTc5ODEyMH0.D6bCoGwCEJ1tiJ0Dsl106GwQpfIVYAWb55zQDmLi7bE

###
GET {{host}}/api/users/1
###
GET {{host}}/api/users/name/alex/1
###
GET {{host}}/api/users/mail/fede@gmail.com

###
GET {{host}}/api/expenses/getDepth/3/2
###
POST {{host}}/api/users/create
Content-Type: application/json

{
    "username": "lola",
    "mail": "lola1@gmail.com",
    "password": "12345"
}
###
PUT {{host}}/api/users/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTczOTc5ODEyMH0.D6bCoGwCEJ1tiJ0Dsl106GwQpfIVYAWb55zQDmLi7bE

{
    "username": "federico",
    "mail": "fede@gmail.com",
    "password": "12345"
}

###
DELETE  {{host}}/api/users/3

###############################################################



GET {{host}}/api/teams


###
GET {{host}}/api/teams/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTczOTc5ODEyMH0.D6bCoGwCEJ1tiJ0Dsl106GwQpfIVYAWb55zQDmLi7bE
###
GET {{host}}/api/teams/name/gym
###
GET {{host}}/api/teams/category/comida

###
POST {{host}}/api/teams/create
Content-Type: application/json

{
    "name": "cena",
    "description": "cena de amigos",
    "category": "comida"
}
###
PUT {{host}}/api/teams/1
Content-Type: application/json

{
     "name": "viaje a Barcelona",
    "description": "viaje de trabajo",
    "category": "comida"
}

###
DELETE  {{host}}/api/teams/1

##########################################

GET {{host}}/api/expenses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTczOTc5ODEyMH0.D6bCoGwCEJ1tiJ0Dsl106GwQpfIVYAWb55zQDmLi7bE
###
GET {{host}}/api/expenses/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTczOTc5ODEyMH0.D6bCoGwCEJ1tiJ0Dsl106GwQpfIVYAWb55zQDmLi7bE
###
GET {{host}}/api/expenses/user/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTczOTc5ODEyMH0.D6bCoGwCEJ1tiJ0Dsl106GwQpfIVYAWb55zQDmLi7bE
###
GET {{host}}/api/expenses/name/cena/1

###
POST {{host}}/api/expenses/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3NDAxMjg1MTN9.qNNfykllI82WD3oN-WkABeK9bW4i2VkBgYezquMHZzs

{
  "name": "salida",
  "amount": 20,
  "teamId": 1,
  "assignations": [
    { "Username": "AlexCastet", "Assignation": 10, "UserId": 1 },
    { "Username": "Lucrecia", "Assignation": 5, "UserId": 2 },
    { "Username": "carlos_valenzuela", "Assignation": 5, "UserId": 3  }
  ]
}
###
PUT {{host}}/api/expenses/4
Content-Type: application/json

{
    "name": "salida",
    "amount": "20"
}

###
DELETE  {{host}}/api/expenses/4

###
POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "alex",
    "mail": "alex@gmail.com",
    "password": "12345"
}
###
POST {{host}}/api/users/login
Content-Type: application/json

{
    
    "mail": "alex@gmail.com",
    "password": "12345"
}