@host = http://localhost:3000

GET {{host}}/api/users


###
GET {{host}}/api/users/1
###
GET {{host}}/api/users/name/carlos

###
POST {{host}}/api/users/create
Content-Type: application/json

{
    "username": "lola",
    "mail": "lola1@gmail.com",
    "password": "12345"
}
###
PUT {{host}}/api/users/3
Content-Type: application/json

{
    "username": "lola",
    "mail": "lola.robles@gmail.com",
    "password": "12345"
}

###
DELETE  {{host}}/api/users/3

###############################################################



GET {{host}}/api/teams


###
GET {{host}}/api/teams/1
###
GET {{host}}/api/teams/name/gym

###
POST {{host}}/api/teams/create
Content-Type: application/json

{
    "name": "cena",
    "description": "cena de amigos",
    "category": "comida"
}
###
PUT {{host}}/api/teams/1
Content-Type: application/json

{
     "name": "viaje a Barcelona",
    "description": "viaje de trabajo"
}

###
DELETE  {{host}}/api/teams/1

##########################################

GET {{host}}/api/expenses

###
GET {{host}}/api/expenses/1
###
GET {{host}}/api/expenses/team/1
###
GET {{host}}/api/expenses/name/cena

###
POST {{host}}/api/expenses/create
Content-Type: application/json

{
    "name": "salida",
    "amount": "20",
    "UserIDCreator": 1,
    "teamId":1
    
}
###
PUT {{host}}/api/expenses/1
Content-Type: application/json

{
     "name": "viaje a Barcelona",
    "description": "viaje de trabajo"
}

###
DELETE  {{host}}/api/teams/1